services:
  mikhmon:
    image: ethergig/mikhmonv3:v3.20-patched-ros7.10
    container_name: mikhmonv3-patched-ros7.10
    restart: unless-stopped
    volumes:
      - data:/var/www/html
    ports:
      - 9000:9000
  
volumes:
  data:
  