services:
  mikhmon:
    image: ethergig/mikhmonv3:latest
    container_name: mikhmonv3
    restart: unless-stopped
    volumes:
      - data:/var/www/html
    ports:
      - 9000:9000
  
volumes:
  data:
  
