services:
  mikhmon:
    image: ethergig/mikhmon:latest
    container_name: mikhmon
    restart: unless-stopped
    volumes:
      - data:/var/www/html
    ports:
      - 9000:9000
  
volumes:
  data:
  